[control_plane]
control ansible_host=13.126.202.121

[workers]
worker ansible_host=3.110.225.151

[kubernetes:children]
control_plane
workers

[kubernetes:vars]
ansible_user=ec2-user
ansible_ssh_private_key_file=/home/kavinaya_r/.ssh/id_ed25519
ansible_python_interpreter=/usr/bin/python3
k3s_server_private_ip=10.0.1.41